### ISSUE TITLE
Improve IRVE logging

### ISSUE THREAD

**Issue by JZJisawesome** [angry-goose-initiative/wiki#8]
Both stop busywaiting and keep the queue from growing without bound.

Also implement batching to improve efficiency if feasible

**Comment by JZJisawesome** [comment]
Let me copy-paste the bullet points Sam and I cam up with the other day:

Async:
- Cap queue size
- Fix busywaiting
- Batch prints to speed up logging thread
- Reduce emulation thread cost at all costs

Sync:
- Reduce function call cost at all costs
 
Both:
- Verbosity control
- Potentially new method of logging (but must retain backwards compatibility). Perhaps using consteval/constexpr?

**Comment by nickchan2** [comment]
@JZJisawesome  By backwards compatibility do you mean the parameters that say `irvelog` accepts? Wondering since for #16 I'm planning on doing away with the logging macros in favor of overloaded functions which would likely be in a namespace (e.g. `irvelog(1, "msg")` would become something `irvelog::info(1, "msg)` ). This kind of change would be super easy to make since we could just use find and replace.

**Comment by nickchan2** [comment]
As discussed today, we won't be moving forward with this
